window.ICLR_META = {
  title: "ICLR 2026 Paper Field Notes",
  updated: "2026-04-18",
  note: "Summaries are short Korean notes based on OpenReview/ICLR metadata and local PDFs.",
};

window.ICLR_PAPERS = [
  {
    id: "11163",
    title: "MemAgent: Reshaping Long-Context LLM with Multi-Conv RL-based Memory Agent",
    authors: [
      "Hongli Yu",
      "Tinghong Chen",
      "Jiangtao Feng",
      "Jiangjie Chen",
      "Weinan Dai",
      "Qiying Yu",
      "Ya-Qin Zhang",
      "Wei-Ying Ma",
      "Jingjing Liu",
      "Mingxuan Wang",
      "Hao Zhou",
    ],
    session: "Oral Session 1",
    slot: "24th 10:30-12:00",
    presentation: "Oral",
    priority: "high",
    status: "todo",
    pdf: "Poster Session 1 (24th 1030-1300)/11163_MemAgent_Reshaping_Long_.pdf",
    source: "https://openreview.net/forum?id=k5nIOvYGCL",
    tags: ["LLM", "memory", "long-context", "agent", "RL"],
    summary:
      "긴 문서를 세그먼트로 읽고 메모리를 덮어쓰며 갱신하는 에이전트 흐름을 RL로 최적화한다. 장기 문맥 extrapolation을 별도 메모리 관리 문제로 다루는 점이 핵심이다.",
    takeaways: [
      "메모리 업데이트 정책을 모델 워크플로의 중심 학습 대상으로 둔다.",
      "짧은 학습 컨텍스트에서 훨씬 긴 QA 설정으로 확장하는 실험을 강조한다.",
      "멀티 컨버세이션 생성과 DAPO 확장이 훈련 안정성에 어떤 역할을 하는지 확인할 만하다.",
    ],
    question: "Overwrite memory가 정보 손실과 추적 가능성에 어떤 trade-off를 만드는가?",
  },
  {
    id: "11338",
    title: "MLP Memory: A Retriever-Pretrained Memory for Large Language Models",
    authors: ["Rubin Wei", "Jiaqi Cao", "Jiarui Wang", "Jushi Kai", "Qipeng Guo", "Bowen Zhou", "Zhouhan Lin"],
    session: "Poster Session 1",
    slot: "24th 10:30-13:00",
    presentation: "Poster",
    priority: "medium",
    status: "todo",
    pdf: "Poster Session 1 (24th 1030-1300)/11338_MLP_Memory_A_Retriever_P.pdf",
    source: "https://openreview.net/forum?id=1SMdxRtLBp",
    tags: ["LLM", "memory", "retrieval", "RAG", "parametric"],
    summary:
      "kNN retriever의 동작을 MLP 모듈에 사전학습시켜 검색 패턴을 파라메트릭 메모리로 내재화한다. RAG의 지연과 파인튜닝의 망각 사이를 줄이려는 접근이다.",
    takeaways: [
      "외부 문서 접근 없이 retrieval-like behavior를 모델 안에 넣는 설계다.",
      "Transformer decoder와 확률 보간 방식으로 붙이는 단순한 통합을 내세운다.",
      "RAG 대비 속도와 hallucination 감소 주장을 벤치마크별로 확인하면 좋다.",
    ],
    question: "새 지식 업데이트가 필요한 상황에서는 MLP Memory를 얼마나 자주 다시 학습해야 할까?",
  },
  {
    id: "1717",
    title: "MemoryVLA: Perceptual-Cognitive Memory in Vision-Language-Action Models for Robotic Manipulation",
    authors: [
      "Hao Shi",
      "Bin Xie",
      "Yingfei Liu",
      "Lin Sun",
      "Fengrong Liu",
      "Tiancai Wang",
      "Erjin Zhou",
      "Haoqiang Fan",
      "Xiangyu Zhang",
      "Gao Huang",
    ],
    session: "Poster Session 1",
    slot: "24th 10:30-13:00",
    presentation: "Poster",
    priority: "medium",
    status: "todo",
    pdf: "Poster Session 1 (24th 1030-1300)/1717_MemoryVLA_Perceptual_Cogn.pdf",
    source: "https://openreview.net/forum?id=54U3XHf7qq",
    tags: ["robotics", "VLA", "memory", "long-horizon", "embodied AI"],
    summary:
      "로봇 조작에서 시간적 문맥을 다루기 위해 working memory와 perceptual-cognitive memory bank를 결합한다. 장기 과제에서 현재 관측과 과거 경험을 함께 쓰는 VLA 프레임워크다.",
    takeaways: [
      "인지과학의 working memory와 장기 기억 구분을 VLA 구조로 옮긴다.",
      "저수준 perceptual detail과 고수준 semantic gist를 함께 저장한다.",
      "시뮬레이션과 실제 로봇 실험의 실패 사례를 보면 적용 범위가 더 선명해질 듯하다.",
    ],
    question: "메모리 검색/병합이 실시간 제어 지연에 얼마나 영향을 주는가?",
  },
  {
    id: "18334",
    title:
      "RAIN-Merging: A Gradient-Free Method to Enhance Instruction Following in Large Reasoning Models with Preserved Thinking Format",
    authors: ["Zhehao Huang", "Yuhang Liu", "Baijiong Lin", "Yixin Lou", "Zhengbao He", "Hanling Tian", "Tao Li", "Xiaolin Huang"],
    session: "Oral Session 1",
    slot: "24th 10:30-12:00",
    presentation: "Oral",
    priority: "high",
    status: "todo",
    pdf: "Poster Session 1 (24th 1030-1300)/18334_RAIN_Merging_A_Gradient_.pdf",
    source: "https://openreview.net/forum?id=PO2iULmu5e",
    tags: ["LLM", "reasoning", "instruction following", "model merging", "alignment"],
    summary:
      "대형 reasoning model에 instruction-tuned model의 장점을 병합하되, thinking/response 형식을 보존하는 gradient-free 방법이다. Null-space projection과 instruction-attention scaling으로 간섭을 줄인다.",
    takeaways: [
      "LRM과 ITM의 task vector subspace가 거의 직교한다는 관찰에서 출발한다.",
      "생각 토큰의 forward feature null space로 투영해 reasoning format을 보존한다.",
      "agent setting에서도 instruction adherence 개선이 이어지는지 확인할 가치가 있다.",
    ],
    question: "형식 보존과 instruction following 개선이 서로 충돌하는 사례는 무엇인가?",
  },
  {
    id: "1991",
    title: "Steerable Adversarial Scenario Generation through Test-Time Preference Alignment",
    authors: ["Tong Nie", "Yuewen Mei", "Yihong Tang", "Junlin He", "Jie Sun", "Haotian Shi", "Wei Ma", "Jian Sun"],
    session: "Poster Session 1",
    slot: "24th 10:30-13:00",
    presentation: "Poster",
    priority: "medium",
    status: "todo",
    pdf: "Poster Session 1 (24th 1030-1300)/1991_Steerable_Adversarial_Sce.pdf",
    source: "https://openreview.net/forum?id=lYNsZdKn5R",
    tags: ["autonomous driving", "adversarial", "preference alignment", "planning", "safety"],
    summary:
      "자율주행 adversarial scenario 생성을 다목적 preference alignment로 재정의한다. SAGE는 재학습 없이 inference 시점에 adversariality와 realism의 비율을 조절한다.",
    takeaways: [
      "고정 trade-off 모델 대신 테스트 시점 steerability를 제공한다.",
      "상반된 preference expert를 만들고 weight interpolation으로 정책 스펙트럼을 구성한다.",
      "닫힌 루프 driving policy 학습에서 실제 안전성 평가로 이어지는지 볼 만하다.",
    ],
    question: "현실성 realism 지표가 실제 도로 위험 분포를 충분히 반영하는가?",
  },
  {
    id: "23970",
    title: "PALC: Preference Alignment via Logit Calibration",
    authors: ["Sanghyun Lee", "Hoh Peter In"],
    session: "Poster Session 1",
    slot: "24th 10:30-13:00",
    presentation: "Poster",
    priority: "medium",
    status: "todo",
    pdf: "Poster Session 1 (24th 1030-1300)/23970_PALC_Preference_Alignmen.pdf",
    source: "https://openreview.net/forum?id=0cmuYj3WeG",
    tags: ["alignment", "logits", "test-time", "LLM", "steering"],
    summary:
      "hidden representation을 직접 조작하지 않고 vocabulary logit 공간에서 preference calibration을 적용한다. frozen LLM에 작고 해석 가능한 test-time alignment 레이어를 붙이는 방식이다.",
    takeaways: [
      "logit 차원이 토큰과 직접 대응한다는 점을 활용해 intervention을 단순화한다.",
      "스케일링 계수 하나로 alignment 강도를 런타임에 조정한다.",
      "guided decoding 대비 지연이 낮다는 주장을 실제 serving 관점에서 확인하고 싶다.",
    ],
    question: "토큰 단위 logit calibration이 장문 생성의 전역 선호를 얼마나 안정적으로 유지할까?",
  },
  {
    id: "24355",
    title: "PERK: Long-Context Reasoning as Parameter-Efficient Test-Time Learning",
    authors: ["Zeming Chen", "Angelika Romanou", "Gail Weiss", "Antoine Bosselut"],
    session: "Poster Session 1",
    slot: "24th 10:30-13:00",
    presentation: "Poster",
    priority: "medium",
    status: "todo",
    pdf: "Poster Session 1 (24th 1030-1300)/24355_PERK_Long_Context_Reason.pdf",
    source: "https://openreview.net/forum?id=qxDTe8fIyA",
    tags: ["LLM", "long-context", "test-time learning", "LoRA", "meta-learning"],
    summary:
      "긴 컨텍스트를 테스트 시점 gradient update로 LoRA 어댑터에 빠르게 인코딩하고, 바깥 루프에서 이를 활용해 recall/reasoning하도록 meta-training한다.",
    takeaways: [
      "LoRA를 장기 컨텍스트용 파라메트릭 메모리로 쓰는 발상이 흥미롭다.",
      "관련 정보 위치와 reasoning complexity에 대한 robustness 분석을 강조한다.",
      "테스트 시점 업데이트 비용과 실제 온라인 사용 가능성을 체크해야 한다.",
    ],
    question: "컨텍스트마다 어댑터를 업데이트할 때 캐싱과 보안 격리는 어떻게 처리할 수 있을까?",
  },
  {
    id: "6247",
    title: "TokMem: One-Token Procedural Memory for Large Language Models",
    authors: ["Zijun Wu", "Yongchang Hao", "Lili Mou"],
    session: "Poster Session 1",
    slot: "24th 10:30-13:00",
    presentation: "Poster",
    priority: "medium",
    status: "todo",
    pdf: "Poster Session 1 (24th 1030-1300)/6247_TokMem_One_Token_Procedur.pdf",
    source: "https://openreview.net/forum?id=RWjEf9PdiJ",
    tags: ["LLM", "procedural memory", "tokens", "continual adaptation", "prompting"],
    summary:
      "반복 사용되는 절차를 하나의 trainable memory token으로 컴파일한다. 프롬프트를 매번 다시 읽는 비용을 줄이고, frozen backbone에 절차 지식을 모듈식으로 추가한다.",
    takeaways: [
      "메모리 토큰이 procedure index이자 generation control signal로 동작한다.",
      "새 절차를 추가해도 기존 절차 간섭을 줄이는 continual adaptation을 내세운다.",
      "RAG prompting과 PEFT 대비 토큰/파라미터 효율 비교가 핵심 체크포인트다.",
    ],
    question: "절차가 복합적이거나 충돌할 때 one-token memory가 충분한 표현력을 갖는가?",
  },
  {
    id: "746",
    title: "VerifyBench: Benchmarking Reference-based Reward Systems for Large Language Models",
    authors: [
      "Yuchen Yan",
      "Jin Jiang",
      "Zhenbang Ren",
      "Yijun Li",
      "Xudong Cai",
      "Yang Liu",
      "Xin Xu",
      "Mengdi Zhang",
      "Jian Shao",
      "Yongliang Shen",
      "Jun Xiao",
      "Yueting Zhuang",
    ],
    session: "Poster Session 1",
    slot: "24th 10:30-13:00",
    presentation: "Poster",
    priority: "medium",
    status: "todo",
    pdf: "Poster Session 1 (24th 1030-1300)/746_VerifyBench_Benchmarking_R.pdf",
    source: "https://openreview.net/forum?id=JfsjGmuFxz",
    tags: ["benchmark", "reward model", "verification", "RL", "reasoning"],
    summary:
      "LLM RL 훈련에서 정답 reference를 기준으로 출력을 검증하는 reward system을 평가하는 벤치마크다. VerifyBench-Hard를 통해 현 verifier의 취약 사례를 드러낸다.",
    takeaways: [
      "응답 선호 비교가 아니라 ground-truth reference 검증 능력에 초점을 둔다.",
      "모델 기반 verifier가 표준 케이스와 hard 케이스에서 어떻게 갈리는지 분석한다.",
      "RLVR/Reasoning 모델 학습 파이프라인 평가 기준으로 연결하기 좋다.",
    ],
    question: "reference가 여러 올바른 풀이를 허용하는 문제에서 verifier 평가는 얼마나 안정적인가?",
  },
  {
    id: "8572",
    title: "Think-While-Generating: On-the-Fly Reasoning for Personalized Long-Form Generation",
    authors: ["Chengbing Wang", "Yang Zhang", "Wenjie Wang", "Xiaoyan Zhao", "Fuli Feng", "Xiangnan He", "Tat-Seng Chua"],
    session: "Poster Session 1",
    slot: "24th 10:30-13:00",
    presentation: "Poster",
    priority: "medium",
    status: "todo",
    pdf: "Poster Session 1 (24th 1030-1300)/8572_Think_While_Generating_On.pdf",
    source: "https://openreview.net/forum?id=lle0aGQyQb",
    tags: ["LLM", "personalization", "reasoning", "long-form generation", "alignment"],
    summary:
      "개인화 장문 생성에서 reasoning을 응답 전에 한 번 끝내는 대신, 별도 reasoning model이 latent token-level reasoning을 병렬 생성해 generation model에 계속 주입한다.",
    takeaways: [
      "FlyThinker는 reasoning과 generation을 동시에 진행해 긴 출력 중 변화하는 문맥에 대응한다.",
      "reasoning model이 이전 응답에만 의존하도록 설계해 학습 병렬성을 유지한다.",
      "개인화 품질과 추론 비용 사이 균형을 실제 long-form task에서 볼 필요가 있다.",
    ],
    question: "사용자 선호가 암묵적이거나 모순될 때 latent reasoning이 어떻게 갱신되는가?",
  },
];
